[package]
name = "roguelike-rust-bevy_ecs-macroquad-noname"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["lib/rs-nonamerl-core", "bin/rs-nonamerl"]


[dependencies]
