[package]
name = "rs-nonamerl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.11.0"
macroquad = "0.4.2"

rs-nonamerl-core = { path = "../../lib/rs-nonamerl-core" }
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.19"
noise = "0.8.2"
rand = "0.8.5"
tracing = { version = "0.1.37" }
tracing-subscriber = "0.3.17"
tracy-client = { version = "*", default-features = false, features = [
    "enable",
] }
